### ISSUE TITLE
Clearify nagiosDateFormat relation to nagios.cfg

### ISSUE THREAD

**Issue by gnanet** [LaMi-/nagios_downtime#6]
Its me again :)

I cannot say my english is excellent, but i had to learn trough my failure that the value of **$nagiosDateFormat** has a 1:1 relation to **date_format** in nagios.cfg, because i did not understand "same like set" as "has to be set same".

 If they differ, the downtime scheduling fails with "Start or end time not valid" because nagios expects the date format specified in its config.

Maybe the line https://github.com/LaMi-/nagios_downtime/blob/master/nagios_downtime#L108 should read:

```
# Nagios date format (has to be set to the same value what "date_format" has in nagios.cfg)
my $nagiosDateFormat = "us";
```

**Comment by LarsMichelsen** [comment]
Thanks. Just updated the comment.
